### ISSUE TITLE
Northern Frisian Messed up (Font Issue?)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#100]
On the /stories page the Northern Frisian entry has a bunch of garbage after it.

**Comment by phillip-hopper** [comment]
@jag3773 The problem is in the api.  This is what is being returned by https://api.unfoldingword.org/obs/txt/1/obs-in-progress.json:

```
[{"lc": "9.%29h%29r%2ad%2ap%2ab%2b1]-%2a6%2az%29m%2av%2a7%2aw]-%291%2ac%2aw%29w%2b1%29w%2aa%2b1]age-en", "ln": "Northern Frisian"},
 {"lc": "aaa", "ln": "Ghotuo"},
 {"lc": "aac", "ln": "Ari"},
 {"lc": "aad", "ln": "Amal"},
 {"lc": "abp", "ln": "Abellen Ayta"},
...
```

**Comment by phillip-hopper** [comment]
@jag3773 Upon further investigation I found there is a `9.%29h%29r%2ad%2ap%2ab%2b1]-%2a6%2az%29m%2av%2a7%2aw]-%291%2ac%2aw%29w%2b1%29w%2aa%2b1]age-en` namespace in the door43.org data.

**Comment by jag3773** [comment]
The export script for this is obs/json/obs_inprogress.py in the tools repo.  This is called everyday from /etc/cron.d/obs_inprogress.

**Comment by phillip-hopper** [comment]
@jag3773 I didn't find anything in the script that would cause this. I think it maybe happened when someone was trying to initialize OBS. I deleted the offending namespace from the door43.org server.
