### ISSUE TITLE
Name of TL language not displaying correctly

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord/unfoldingWord.github.io#103]
![image](https://cloud.githubusercontent.com/assets/5262964/10820957/3bb00f10-7e26-11e5-9517-5f68c3f66e86.png)

See `Wikang Tagalog` in the image.  At this time I'm not sure if the problem is bad data or a missing font.

**Comment by jag3773** [comment]
This is still an issue.

**Comment by jag3773** [comment]
Data issue is fixed.  Site will be fixed on next generation.
