### ISSUE TITLE
tA HTML

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#105]
Related to #98.

We need to get tA pulling from the JSON representation, modeled at http://td-demo.unfoldingword.org/publishing/ta-en.json.

**Comment by phillip-hopper** [comment]
@jag3773: I've found 2 problems with the ta-en.json data:
- Many of the 'src' and 'href' attributes have relative URL values that are only valid on door43.org. `src=\"/_media/en/ta/translation_process.png?w=600&amp;h=360&amp;tok=398a59\"`
- The 'title' attributes of the 'a' tags have Dokuwiki references rather than valid titles. `title=\"en:ta:vol1:translate:translate_retell\"`

Created issues in the tD repo for there: unfoldingWord-dev/translationDatabaseWeb#296, unfoldingWord-dev/translationDatabaseWeb#297

**Comment by jag3773** [comment]
We need to get all the links in the document working.  In particular, the links in the Finding Answers section are not all working.  A few things that we need to have happen:
- [x] Email address is a mailto link
- [x] Internal links work within the doc
- [x] The en/slack link is actually something that should point to https://door43.org/en/slack.  Is there a way to preserve that as pointing to Door43?  Or do we need to change something in the source?

**Comment by richmahn** [comment]
For the en/slack one I know that I could just look for /en/slack and add the door43.org domain to it.

**Comment by ChrisJarka** [comment]
I noticed that the links such as - https://slack.com/en/ta/vol1/intro/toc_intro.pdf on page 8 are not valid. Is this the same issue as Jesse pointed out?

**Comment by ChrisJarka** [comment]
It looks like something is 'off' for some of the Checking Manual pages. For examples: 131 and 132, 136 and 137 might need to be on the same page? Check with Ben or Perry

**Comment by benjore** [comment]
**Absolutely needed**: the order of the modules need to show up in the same order as they appear in the Table of Contents in Door43. 
**Strongly preferred**: In most of the TOCs there are subheadings that introduce a clump of modules (e.g. in the Translation Manual Volume 1, the first subheading is Introduction which intros the first 4 modules, the second is "Defining a Good Translation" which intros the next 5, etc). Having these subheadings will greatly help in being able to find content in the TOC.

**Comment by benjore** [comment]
**Strongly preferred**: if at all possible, it would be very helpful if the hierearchy of the TOC could be kept.

**Comment by richmahn** [comment]
@benjore As you see Jesse referenced, that is also an issue, #301 in the translationDatabaseWeb repo. This issue is more for what Phil and I have to do once we get the "raw" data.

**Comment by phillip-hopper** [comment]
From @benjore:

> Is it possible to make headers that look like this ( == header == ) have a little bit bigger font as it looks the same size as the normal text? See https://test.unfoldingword.org/academy/#direct-replacements

Need to modify the `h5` style to fix this.
