### ISSUE TITLE
Create Network Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#111]
Wee need to create a /network page that will list all the the nodes in the unfoldingWord network, ideally with logos as well.  Potentially this could take the shape of a generator that iterates through a list of names and logos and generates the page.

**Comment by codemis** [comment]
@jag3773 Can you tell me where to find the nodes in the unfoldingWord network?

**Comment by jag3773** [comment]
@codemis can you setup the file I suggested in the OP and then I can start adding names in.
