### ISSUE TITLE
Two Entries for 'vi' on /stories page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#112]
There are 2 entries for 'vi' on the /stories page.  I only see it listed once in http://td.unfoldingword.org/exports/langnames.json, although the name was recently updated.

Perhaps the site regen needs to refresh its language information via  http://td.unfoldingword.org/exports/langnames.json to make sure it is up to date?

**Comment by codemis** [comment]
@jag3773 I think this issue should be closed.  I am only seeing 1 'vi' on the /stories page.  The language information is currently being pulled from http://td.unfoldingword.org/exports/langnames.json in the generator script.
