### ISSUE TITLE
Move Reveal Slideshows Here

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#113]
The reveal slideshows are currently generated from https://github.com/unfoldingWord-dev/tools/blob/master/obs/js/reveal_export.py and end up in the api docroot.

Some files are also pulled from the old (wordpress) unfoldingword website (like js/obs-notes.js).

Let's unite all of that into our codebase here, ensuring that the reveal slideshows are built when the site is built.  Note that you don't have to rewrite reveal_export.py, you could just call it from Jekyll when the site is generated.

If we can prevent duplicated files, then let's do that, too.  In other words, if obs-notes.js is the same for all languages, then let's just put that in one location and call it appropriately.

Then, let's actually move the slideshows to run out of the unfoldingword.org docroot.  Probably at /[lang_code]/obs/slides, for example https://unfoldingword.org/am/slides/360px/.

Last thing to keep in mind is that we would like to be able to provide a download (zip file?) of these slideshows per language.  In other words, if we could make it easy for someone to download the slideshow for their language then they could run it in their browser when they are offline.  Or maybe we want to do this via a Chrome extension or glorified browser caching?  Note: this is not a todo on this issue, just something to keep in mind as you rearrange files and code.

Todos for this would be something like:
- [x] Move reveal_export.py to this codebase
- [x] Move supporting js/html files to this codebase (like obs-notes.js)
- [x] Trigger slideshows to be rebuilt when site is rebuilt
- [x] Unify location of js/html files that are the same for every language
- [x] Set output to be relative to language in this site's docroot

**Comment by codemis** [comment]
@jag3773 Should we leave the script in Python?  Developers will need to install both Python 2 and Ruby in order to work on the code base.  Is that what you would prefer?

**Comment by codemis** [comment]
Ok,  I moved everything over to the uW main site. I pushed up a branch named **obs_slides** with the changes.  Currently, it is using a generator to call the Python script during the site build process.  If you want me to convert the Python to Ruby,  I can do that.  Just let me know.  Please let me know if everything looks good, and I will merge it into **master**.

**Comment by phillip-hopper** [comment]
@codemis: It may be a good idea to convert the Python script to Ruby. It would certainly make debugging simpler.

**Comment by jag3773** [comment]
@phillip-hopper can you review the changes in `obs_slides` ?

**Comment by codemis** [comment]
@jag3773 Should I leave the Python script or move it to Ruby?  Which do you prefer?

**Comment by phillip-hopper** [comment]
The only thing I noticed during the review of the `obs_slides` branch was the "next" and "previous" arrows in the lower right corner are very difficult to see sometimes if the text is short. Other than that, it looks good.

![image](https://cloud.githubusercontent.com/assets/5262964/12534076/523a5c92-c217-11e5-8d63-e33bf0ff7802.png)

**Comment by jag3773** [comment]
@phillip-hopper no problem on that... or rather, if we want to fix that then let's create a new issue for it.  @codemis 's changes wouldn't have affected that.

:shipit:
