### ISSUE TITLE
JS Zip Utility for S3

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#115]
Can we get https://stuk.github.io/jszip/ and https://github.com/rgrp/s3-bucket-listing/blob/gh-pages/index.html working together so that we can create a zip of files on an S3 server client side?  For example, I have a folder of 50 mp4 files on S3, I don't want to store each of them and a zip file, so it would be nice if we had a JS utility that could zip them so that a user could download all of them with one click.

**Comment by codemis** [comment]
This was pushed to a system admin to build a server side script for it.
