### ISSUE TITLE
(POD) Alter Source Text on Door43

### ISSUE THREAD

**Issue by zoofries** [unfoldingWord/unfoldingWord.github.io#135]
Add break between, _'an unrestricted visual mini bible’_ and _‘in any language’_ to aid in automating cover production.

**Comment by jag3773** [comment]
This is where the text would need changed https://git.door43.org/Door43/en-obs/src/master/content/_front/front-matter.md .  But its still unclear if this is the best way to go about making the change.

**Comment by jag3773** [comment]
We can't change the text there because it will throw off the front matter page.  For now we are going to close this issue, we'll revisit it once the live.door43.org site is up and running and we have a better idea of whether or not we'll need this feature.
