### ISSUE TITLE
Add tooltips for All Languages

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#143]
Would be good if we could add tooltips for all language codes that show up on the site.  This would be similar to the few that are setup on the /gateway/ page.

A few requirements:
- [ ] This cannot add extra overhead to loading a page
- [ ] This should support any code used on a page
- [ ] The data source is http://td.unfoldingword.org/exports/langnames.json (big file)
- [ ] The above data source should only be hit when absolutely necessary (e.g. cache the file and don't request it again unless you have to)

The above coalesce to suggest that this should be some sort of Jekyll plugin that runs when the site is built.  Perhaps this runs for each page and automatically adds the relevant crib sheet information like we have on the /gateway/ page?  That way nothing extraneous would happen on any page load for the user.

**Comment by codemis** [comment]
@jag3773 If we have it automatically parse content, how will we handle false positives? For example, hi is the code for हिन्दी, हिंदी.  Maybe we could use a [Liquid Tag](https://jekyllrb.com/docs/plugins/#tags) to handle this.  We will have to go through the code and replace all instances of the code with the tag version, but it will protect from false positives.  Thoughts?

**Comment by jag3773** [comment]
I'm thinking about a hybrid between the short links and tooltips.  For short links we put `[contact us][contact]` in the page and we put `[contact]: {{ '/contact' | prepend: site.baseurl }} "Contact us!"` at the end of the page.

Could we put `[en][en]` in the page with the tooltip text at the bottom as `*[en]: English` ?
