### ISSUE TITLE
Fix `<i>` Element on /academy/

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#152]
It is reported that there is an HTML `<i>` element on the /academy/ page.  Let's not do this.

**Comment by phillip-hopper** [comment]
@jag3773: This is being used for font awesome, and it is the normal way to do it according to the documentation. I will research alternatives.

**Comment by jag3773** [comment]
Let's skip it then @phillip-hopper , you're right about it being normal for font awesome.
