### ISSUE TITLE
Phase 3.1 - Create deployment utility

### ISSUE THREAD

**Issue by phillip-hopper** [unfoldingWord/unfoldingWord.github.io#16]
1. create utility (script) that zips the entire website as a fully-functional, static, ofine website
   that works in any browser (after unzipping)
2. develop a means of choosing which languages are included in the zip file (or default to
   zipping up all languages in a given region of the world, etc.)

**Comment by jag3773** [comment]
Note that Github already provides a zipball of master, so it would be ideal
if we could utilize that.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
