### ISSUE TITLE
Move all markup + header content to _layouts/default.html

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#17]
Data like this:

```
<div class="site-inner">
  <div class="content-sidebar-wrap">
    <main class="content" role="main" itemprop="mainContentOfPage">
      <article class="page type-page status-publish entry" itemscope="itemscope"
               itemtype="http://schema.org/CreativeWork">
        <header class="entry-header"><h1 class="entry-title" itemprop="headline">unfoldingWord Bible</h1>
        </header>
        <div class="entry-content" itemprop="text">
```

should all be in the template (layout) html, so that the content pages can be in clean Markdown. The page title should be passed as a YAML parameter to the layout display. In the example above:

```
title: unfoldingWord Bible
```

Should be passed as a variable to dynamically set the `<h1>unfoldingWord Bible</h1>` for the page.

**Comment by timjore** [comment]
Note: the "about.md" page shows the simplicity of the page layout we should have when the default template works as advertised: all meta info in the YAML header, clean Markdown content in the body of the file.

**Comment by phillip-hopper** [comment]
I will look for a solution that does not involve having the opening html tags in one file and the closing tags in a different file.  That makes it unnecessarily difficult to maintain.
