### ISSUE TITLE
Build and Deploy Site with Travis CI

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#173]
## Story

As an _admin_ I would like Travis CI to build this Jekyll site so that I don't have to maintain a server to do it.
## Notes

See how this was implemented in https://github.com/unfoldingWord-dev/door43.org/issues/1.  The relevant files that need updated would be:
- .travis.yml
- Gemfile
- cibuild.sh
- s3_{prod|dev}_push
- Credential files
- Makefile
- README for devs

Note that the issue of syncing the assets directory is still outstanding (https://github.com/unfoldingWord-dev/door43.org/issues/60)
## History

Quoting from @jag3773 posting elsewhere:

> We could go completely serverless with our Jekyll configuation if we implemented https://github.com/mneumegen/jekyll-lambda-demo as our site builder.
> 
> Effectively, anytime a commit hits this repo then a webhook could trigger that Lambda script above to generate the site in test S3 buckets. Similar to how it works now, the master branch would also be the production S3 bucket. Whenever a merge to master happened then the site would be published again.

Should we do this for the uW site? Development workflow could also start using a `staging` branch or some kind of workflow that enables testing of commits in a separate branch (also auto-built by the lambda service in a different S3 bucket) before merging into production?

**Comment by jag3773** [comment]
Completed finally with 2fd4edf5689312eba785964583c9a1b3327e627b
