### ISSUE TITLE
Update Image Links for OBS Slides

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#174]
All languages need to have their image links for OBS stories updated to use the following link patterns:
- https://cdn.door43.org/obs/jpg/360px/obs-en-11-04.jpg
- https://cdn.door43.org/obs/jpg/2160px/obs-en-11-04.jpg

Replace the '11' and '04' with the appropriate story and frame number, but _do not replace the `en`_.

**Comment by phillip-hopper** [comment]
Done.
