### ISSUE TITLE
web app won't load content on first visit

### ISSUE THREAD

**Issue by Daniel-Hug** [unfoldingWord/unfoldingWord.github.io#176]
This seems like a great project from what I've seen! Thanks! I found out about it [here](https://www.facebook.com/groups/208061215959591/permalink/1040659402699764/?comment_id=1040689072696797&comment_tracking=%7B%22tn%22%3A%22R0%22%7D).

My first visit to the web app was here: https://bible.unfoldingword.org/

I'm on Chrome 51.0.2704.103 m with Windows 10.

This is what it looks like for me (I see [Elijah Elkins had the same issue](https://www.facebook.com/groups/208061215959591/permalink/1040659402699764/?comment_id=1040689072696797&reply_comment_id=1041319325967105&comment_tracking=%7B%22tn%22%3A%22R%22%7D)):
![screenshot-bible unfoldingword org 2016-07-29 21-23-41](https://cloud.githubusercontent.com/assets/1326984/17268089/2105cac6-55d3-11e6-9315-fd67c379ead4.png)

Here's a paste of the console messages:

```
font noto
textsindow init Object false bible
Failed to load resource: the server responded with a status of 403 (Forbidden)
ERROR TextInfoLoader.getText content/texts/uw_en_ulb/info.json
ERROR uw_en_ulb doesnt exist
Uncaught ReferenceError: newTextInfo is not defined
Uncaught TypeError: Cannot read property 'title' of null
Uncaught TypeError: Cannot read property 'id' of null
chooser has not textInfo!
clickoff version picker onshow
clickoff version picker doc.click true
clickoff version picker onhide
```

I found a link to a specific chapter and that loaded well: https://bible.unfoldingword.org/?w1=bible&t1=uw_en_ulb-en&v1=GN1_1

The console output is much cleaner too:

```
font noto
v textid t
v fragmentid v
t textid t
t fragmentid v
textsindow init Object false bible
```

Then I went back to the webapp homepage and it loaded fine.

I replicated this with Chrome incognito with the same results.
opening the homepage fails, but then opening [this](https://bible.unfoldingword.org/?w1=bible&t1=uw_en_ulb-en&v1=GN1_1) works, then opening homepage again works.

**Comment by jag3773** [comment]
Hi @Daniel-Hug, we just pushed the fix out for this earlier today.  Could you verify that it is fixed on your end too?  You'll likely need to clear your browser's cache.

**Comment by Daniel-Hug** [comment]
Looks good now.
