### ISSUE TITLE
Make tS Download a Direct Link

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#185]
## Story

As a *user* I want to be able to download tS right from the uW website so that I don't get lost on Github.

## Notes

The main caveat here is that we need to setup some sort of process to remind us to update the link whenever we make a new release.

**Comment by da1nerd** [comment]
@jag3773 you can get a direct link to download the latest release on github.

**Comment by jag3773** [comment]
Do tell @neutrinog !

**Comment by da1nerd** [comment]
https://github.com/unfoldingWord-dev/ts-android/releases/latest

**Comment by jag3773** [comment]
That does help but it doesn't link directly to the downloadable file.  The OP is asking for a direct link to download the apk, dmg, or exe file.

**Comment by jag3773** [comment]
Fixed in 5442be882f3479ca99ef372f23597d5325bca63e
