### ISSUE TITLE
Rewrite URLs to lose the trailing slash

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#19]
All pages that have a "directory/index.html" format should not require the trailing slash. For example, the page:

unfoldingWord.org**/about/** 

should not require the trailing slash. It should be: 

unfoldingWord.org**/about**

**Comment by dsm-git** [comment]
Currently they do not _require_ the slash.  You can visit
http://unfoldingword.github.io/about and get the page.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer
