### ISSUE TITLE
Update tN, tW, tQ Pages to Pull from Manifest

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#216]
Like the ULB/UDB updates in https://github.com/unfoldingWord/unfoldingWord.github.io/pull/211 .

Task is to update tN, tQ, tW pages so that:

* [x] The page is built primary from the information in the manifest files
* [x] The latest English PDFs are accessible from the main page

Scope:

* [x] tN
* [x] tQ
* [x] tW

**Comment by phillip-hopper** [comment]
@jag3773 I see that for ULB, UDB and tA the links to content have the hash hard-coded in the markdown but the version number and release date are pulled from the manifest. It this the way it should work?

**Comment by jag3773** [comment]
A few tweaks needed:

* Please omit the "view on the web" button for tN, tQ, tW as we haven't built processors for those.
* Please add a download PDF button for the tN resource, I only see the book by book options
