### ISSUE TITLE
OBS page footer

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#231]
_From @mondele on August 22, 2017 15:8_

## Story

As a help desk user I want to direct inquiries so that people can find out the details of licensing for Open Bible Stories.

Currently, in Safari on OS X 10.11 El Capitan, the footer text at https://unfoldingword.org/stories/ is not selectable, and the links are not functioning (because there is a layer between the user and the text).

_Copied from original issue: unfoldingWord-dev/door43.org#675_

**Comment by mondele** [comment]
FYI - this is still an issue. Safari 11.0.2. The issue also exists in Brave Browser for Mac, Chromium 60.0.3112.90 on Mac, and Opera 45.0 for Mac.

**Comment by jag3773** [comment]
@mondele Thanks for bringing this up.  We will be deprecating that page soon and linking to the OBS content on the newly setup https://openbiblestories.com site.
