### ISSUE TITLE
Setup Language Landing Pages

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#24]
Every language with published content should have it's own page at unfoldingword.org/[langcode]/.  These pages should be localized into that language and should list all of the content that we have available in that language.

**Comment by timjore** [comment]
Can we create these pages from Door43 and auto-generate the HTML or Markdown for inclusion in the uW static site? It would be great to have them in a subfolder on the filesystem (e.g. something like `langs/<lang_code>/<lang_assets>`, but build the pages with meta information in the header so they render and display at `uW.org/<lang_code>`. That way we can exclude the `langs` directory from the Git repo and possibly symlink it as needed. What do you think?
