### ISSUE TITLE
switch entire site to use Google Noto fonts

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#28]
Some considerations:
- we can use the Google webfonts for online, but need to also embed the fonts locally for offline use
- the CSS should provide a cascade for font preference that covers every language in a subset of the Noto (similar to the issue encountered by the LaTeX programmers)
- the fonts should be identified in the SASS file so we only need to adjust font names in one location

**Comment by phillip-hopper** [comment]
@timdsm , do you have a recommendation for how to handle Chinese, Japanese and Korean, the NotoSansCJK fonts? They are definitely too big to be treated as web fonts. Each file is over 15 MB.

**Comment by timjore** [comment]
For now, we could just default to the existing system fonts. We may need to load web fonts by namespace... Not sure how hard that would be to do.

**Comment by phillip-hopper** [comment]
The code work is done for this, it just needs tested on the live site.
