### ISSUE TITLE
define variables for downloadable assets

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#42]
create a .yml file that lists every downloadable asset as a named variable, for example:

```
"qa-pdf" : /assets/docs/Quality Assurance of Open-Licensed Biblical Content - rev 14.pdf
```

this variable can be referenced anywhere the URL for the file is desired, for example:

```
...download the [PDF]({{qa-pdf}}).
```

**Comment by timjore** [comment]
The variable definition should also support a "revision number" that can be referenced as a variable in the Markdown, e.g. `<doc>-pdf` is the URL and `<doc>-rev` is the revision number.

**Comment by timjore** [comment]
Great work! Exactly the structure I was looking for. One minor request: can we make the variable name that is referenced in the .md file the shorter name from the `assets.yml` declaration, e.g. `{{ legal-release-pdf.url }}` (and the corresponding `...-pdf.rev`) instead of `{{ site.data.assets.legal-release-pdf.url }}`. As we continue to add large numbers of multi-format assets, this will greatly reduce the complexity and readability of the files.

**Comment by phillip-hopper** [comment]
@timdsm , no, there isn't. The shortest they could be is {{ site.legal-release-pdf.url }} if you want to put them in the _config.yml file. I'll do some more research to see if there is a way to do it with a plugin.

**Comment by phillip-hopper** [comment]
@timdsm , I was able to use a filter to approximate what you asked for with the assets. Instead of {{ site.data.assets.license-pdf.url }} we can set it up to be {{ 'license-pdf'|url }}. The name of the variable needs to be inside quotation marks (single or double, both work). Let me know if you prefer the filter option over the way it is currently set up.
