### ISSUE TITLE
CSS: add third level for main menu

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#45]
I need to create three levels of menus in the main menu, but the CSS appears to only support two. Something like this:

```
[1] About
   |
   + Strategy
   |  |
   |  + Gateway Languages
   |  + Bible Translation 3.0
   |
   + License
```

**Comment by phillip-hopper** [comment]
The css does support 2 sub-levels below the main menu item, but not 3.  I updated the menu code to allow as many sub-levels as needed, but I didn't update the css.  Moving to Bootstrap may take care of that.
