### ISSUE TITLE
need accessible means of pushing updated content to production

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#46]
use case: as new content is made available and the site is improved, I need to be able to push the changes to the production server on-demand.

implementation: consider setting up a "production" branch on a server with a git hook that auto-generates the site and pushes the updates to the production server.

**Comment by jag3773** [comment]
This will be as simple as running `make publish`.

**Comment by timjore** [comment]
what is the status on this? Do I need to configure anything on OS X before I can `make publish` the site? :stuck_out_tongue_winking_eye:
