### ISSUE TITLE
define "header image" and "header title" variables in page meta info

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#57]
Check out this page: https://kato.im/about

That is what I would like for certain pages on the unfoldingWord.org site. I would like to be able to declare a value for the "header image" (e.g. /assets/img/header1.jpg) and a "header title" (e.g. "About unfoldingWord") and have the page layout template do the rest.

Notes:
-   The "header title" should be the `<h1>` element on the page, though the `<title>` info for the page will still be set from "title" variable
-   The image size needs to be established and all header images will be cropped accordingly
-   The "header title" should display in white font and will assume a dark image background. _Bonus: provide a switch in the header to flip that to dark text (on light image)._

Tasks:
- [x] Header image
- [x] Header image style
- [x] Header title
- [x] Header title style

**Comment by phillip-hopper** [comment]
Trello card: [https://trello.com/c/USlBV0sj](https://trello.com/c/USlBV0sj)

**Comment by phillip-hopper** [comment]
@timjore: Have you tested this to see if we can close this issue?

**Comment by phillip-hopper** [comment]
@timjore: Can this be closed now?

**Comment by timjore** [comment]
Yes
