### ISSUE TITLE
Optimize template for efficient page display

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#63]
Perform audits on the front page and other pages of the uW website and adjust rendering so that pages display as rapidly as possible

**Comment by phillip-hopper** [comment]
Part of this will be accomplished during the switch to Bootstrap #15

**Comment by phillip-hopper** [comment]
Trello card: [https://trello.com/c/88pjwlQy](https://trello.com/c/88pjwlQy)
