### ISSUE TITLE
need means of displaying images in a lightshow on click (tap)

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#68]
Instead of merely having images embedded not the page, I need a way to be able to show a thumbnail or smaller version of the image that, when clicked or tapped, displays a larger version of the same image in a lightshow (dark translucent background).

Bonus points: 
-   all images on the page are part of the same album and can be progressed through one image at a time.
-   album display is "swipeable" on touchscreen devices

**Comment by phillip-hopper** [comment]
Trello card: [https://trello.com/c/qpokNIl3](https://trello.com/c/qpokNIl3)
