### ISSUE TITLE
API Index Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#7]
(lower priority than main site, also slightly mis-categorized in this repo ;)
We need api.unfoldingword.org to be a nice looking index page that includes:
- Documentation on how to use:
  - tK API
  - tS API
  - uW API
  - API Cloning information
- Link to browse the API

This needs to be a simple one page index that looks similar to the unfoldingword.org site.  Page should have an in page menu, similar to http://getbootstrap.com/css/.

The API documentation is already written on http://door43.org/en/dev/api.  We should be able to import that wholesale.  The only part lacking is the API cloning information, which I can add when the page is setup.

**Comment by phillip-hopper** [comment]
Trello card: [https://trello.com/c/YtwjPzQq](https://trello.com/c/YtwjPzQq)

**Comment by jag3773** [comment]
Minor issues to fix:
- [x] Need a link to browse the API.  e.g. https://api.unfoldingword.org/ should remain as is, but what you have drawn up will likely become README.html.  So we'll need a link on your page to go back to the root.
- [x] Incorporate Mirroring notes in https://api.unfoldingword.org/README.html
- [x] Fix app spelling.  Should be unfoldingWord, translationStudio, etc.  Same with doc title.
- [x] Logo should link back to unfoldingword.org
