### ISSUE TITLE
need a Print CSS stylesheet

### ISSUE THREAD

**Issue by timjore** [unfoldingWord/unfoldingWord.github.io#71]
Make it as easy as possible for a very clean, minimalist printout of any page on unfoldingWord.org. When hitting Control-P (or "File->Print") the stylesheet should be triggered automatically.

Second, I need a means of exporting select pages (through Pandoc) to .doc format. The goal is to be able to write content directly in the .md files, upload images, publish to the web, then be able to export directly from the web as a .doc. It would seem the same CSS solution for printing might also work here.

**Comment by jag3773** [comment]
Superseded by #87
