### ISSUE TITLE
Include In Progress on OBS Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#72]
We need to include in progress translations on the /stories page.  This catalog provides a list: https://api.unfoldingword.org/obs/txt/1/obs-in-progress.json.

**Comment by codemis** [comment]
@jag3773 Ok.  I included a progress translation section.  You can see it on the [Test Server](https://test.unfoldingword.org/stories/).  Please let me know if you want to make it live.
