### ISSUE TITLE
Change OBS download link to PDF icon

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#78]

**Comment by codemis** [comment]
Ok,  I changed the icon.  Here ya go: https://test.unfoldingword.org/stories/

**Comment by ufw** [comment]
I'm not crazy about that one, I think the font awesome pdf icon may match
the existing ones better?  See
http://fortawesome.github.io/Font-Awesome/icon/file-pdf-o/.

Thank you,
Jesse Griffin
unfoldingWord Chief Technology Officer

**Comment by codemis** [comment]
Ok.  I changed it to the Font Awesome version.
