### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#84]
We need to make some tweaks to the /dashboard page.

Some items to start with:
- [x] #82 JS countdown timer
- [x] Add bootstrap TOC navigation, like /academy page

Possibly:
- [ ] Percentage of opened, opening GLs
- [x] Number of published resource/langs in uW catalog (e.g 10 OBS, 5 Bible)
- [x] Number of in progress resource/langs (e.g. 40 OBS translations)
- [ ] Total number of languages with adequate biblical content

A lot of these metrics can come out of the API, some may need help from tD.

**Comment by jag3773** [comment]
I think this page should have the appearance of an infographic.

**Comment by DonRitchey** [comment]
February 8, 2016:  Additional Dashboard request from Tim Jore (related to Help Desk Ticket 1766):
Please provide an easily maintained (when adding & rearranging content) Table of Contents to the https://unfoldingword.org/dashboard page, similar to the one used on the translationAcademy web page. Ideally, this would be auto-generated from the <heading> sections, either in JavaScript or as part of the build process in Jekyll.

February 8, 2016:  Additional Dashboard request from Tim Jore (related to Help Desk Ticket 1767):
Please provide the icons for each resource (where applicable) on the https://unfoldingword.org/dashboard page, probably about 48px in size, to the left of the top-level header for the content.

**Comment by codemis** [comment]
Waiting for numbers to be added to API, and then we will decide whether to use Javascript or Liquid Template variables for displaying the dashboard stats.

**Comment by codemis** [comment]
Still have a few things to complete here, so I am reopening the issue.  Also,  @phillip-hopper suggested moving all the API URL's to a central place for easier configuration.
