### ISSUE TITLE
Print Stylesheet

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#87]
When printing pages from the unfoldingWord website, a print stylesheet should be triggered that optimizes the page for printing, including:

— proper margins
— decent line spacing
— Google Noto font at 11pt
— no menu, header, or footer elements
— small logo and link to source url at end of printout

c.f. http://www.smashingmagazine.com/2011/11/24/how-to-set-up-a-print-style-sheet/

**Comment by codemis** [comment]
I added all the print styles in the print.scss for all the pages.  I published the changes since there are no breaking changes.  

@jag3773: Please close if everything looks good.
