### ISSUE TITLE
Version Comparer

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#89]
Depends on unfoldingWord-dev/uwadmin#47.  We need a simple and easy to use version comparer for resources published through unfoldingWord.

The user should be able to select the project (OBS, tW, tA, ULB, etc) and language (en, fr, aaa, etc) and then they would be presented with 2 drop downs for comparing 2 revisions (seeded with the published history for that project-language combination).

**Comment by jag3773** [comment]
Currently we have a few different things put together:
- By hand https://door43.org/en/obs/change-log
- By script: https://github.com/unfoldingWord-dev/tools/blob/master/obs/json/comparer.py, which yields something like https://door43.org/obs-diffs/ver_1-to-ver_3.html and https://door43.org/obs-diffs/ver_2-to-ver_3.html.

JS that reads from the catalog and provides the interface would be nice so that we don't need a server side component for this piece.

**Comment by ufw** [comment]
> JS that reads from the catalog and provides the interface would be nice so that we don't need a server side component for this piece.

Yes, that would be really helpful. Something that lists the frames under their respective stories and provides a menu for AJAX-ified navigation between the frames would be spectacular.

**Comment by jag3773** [comment]
More information:

The plan we would like to implement is something like this:

— on the first of every month (or some set date), all resources that have new content of any sort since the last version was published are re-published as an incremental version update with all the new changes. Note: this should not include typo corrections as new versions. e.g. If "tN Ezekiel, English [en]” was at version 1 in June, had no changes in July, but was updated with new content in August would be published on 1 September as “tN Ezekiel, English [en], version 2”

— in order to make it easy for anyone (like GL translators) to see what has changed between the versions, we need a web app (versions.unfoldingword.org? td.unfoldingword.org/versions? ) that provides simple controls enabling the user to:
1. Choose the resource
2. Choose the language
3. View information pertaining to each and every version of the selected resource in the uW catalog
4. Using a slider (or something) generate changelogs on demand between arbitrary versions of the resource.

e.g., a GL translator has an original translation of tW that is based on version 2 of the English. Thus, their translation is “tW, Vietnamese, version 2.1” If the English tW is up to version 8, they would drag the slider to show what changed between “tW, English, version 1” and “tW, English, version 8”. The display should be visually easy to read and exportable to PDF. Note: all these changelogs could be automatically generated on the server with every new version that is published, making them available as PDFs in advance of users needing them, or they could be dynamically generated as needed.

**Comment by jag3773** [comment]
Most of this should be taken care of in this issue https://github.com/unfoldingWord-dev/door43.org/issues/77 .
