### ISSUE TITLE
Fix Menu Wrapping Issue

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#95]
We need to fix the menu drop down so that the s on translationQuestions is not hanging in never never land.  See pic.
![uw-menuwrappingissue](https://cloud.githubusercontent.com/assets/107731/9208393/7c396394-4030-11e5-91cc-49f202fb2c0a.png)

**Comment by jag3773** [comment]
Issue seen in Chrome and Firefox on Linux.

**Comment by ufw** [comment]
The width of the menu should have a minimum (current width is fine) but then the actual width should scale as needed to fit all the entries without wrapping.
