### ISSUE TITLE
Create OBS Audio/Video Page(s)

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#96]
We need a page, probably one per language that provides links to the audio and video for each OBS story.  It may make sense to show a small icon of the first frame of each story with the title for the list.  We'll also want to provide zip files to download all of them at once.

We'll want to add an icon to the /stories page for each language that links to this page.

**Comment by jag3773** [comment]
@sampeckham In the mockups I think this part of the language pages is missing.  There should be a drop down where audio or video can be downloaded per story.  Can you draw something up for that?

**Comment by jag3773** [comment]
The individual audio files are linked to on https://unfoldingword.org/en/?resource=open-bible-stories, but we also need the individual video files to be linked to there.

**Comment by codemis** [comment]
@jag3773: Currently the video url's are not in the catalog.  Where can I get the video URLs?

**Comment by jag3773** [comment]
They follow a pattern similar to the mp3s, for now let's put it in the Jekyll code, version 3 of the API will have links, but we can't wait for that...

https://cdn.unfoldingword.org/en/obs/v4/360p/en_obs_01_360p.mp4
https://cdn.unfoldingword.org/en/obs/v4/720p/en_obs_01_720p.mp4

Thanks @codemis
