### ISSUE TITLE
Notes do not Align with Text in Web Viewer

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#97]
On the web viewer of Open Bible Stories, the tN & tW do not match the story, but always line up with story 01. See for instance https://api.unfoldingword.org/obs/txt/1/en/slides/360px/24/index.html#/2 .

**Comment by jag3773** [comment]
Also, see the new catalog endpoint that notes what translationWords show up in each frame: https://api.unfoldingword.org/obs/txt/1/en/tw_cat-en.json.  That URL is referenced in the resources catalog now: https://api.unfoldingword.org/ts/txt/2/obs/en/resources.json.

**Comment by jag3773** [comment]
Code is at https://github.com/unfoldingWord-dev/tools/blob/master/obs/js/reveal_export.py

**Comment by codemis** [comment]
@jag3773 Can we close this issue?  It has been fixed, and once approved, it will move to the uW website. See issue #113
