### ISSUE TITLE
tA Draft

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#98]
We need to get tA onto the unfoldingWord website  The resource is mostly complete but we are still making some tweaks, hence we need to label this as a draft.

@phillip-hopper has worked on a render to HTML script that can likely be used as the basis for this (output of that is at https://api.unfoldingword.org/ta_export.html).  I'm envisioning something imminently navigable, perhaps similar to http://getbootstrap.com/2.3.2/components.html.  This should probably show up directly on https://unfoldingword.org/academy/.

**Comment by jag3773** [comment]
Related to unfoldingWord-dev/Door43#96.

**Comment by phillip-hopper** [comment]
See http://getbootstrap.com/components/
