### ISSUE TITLE
Fix Font for sgj

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/unfoldingWord.github.io#99]
The Surgujia (sgj) OBS was just published and the font is not correct in the web viewer. https://api.unfoldingword.org/obs/txt/1/sgj/slides/360px/01/#/.  The font does look correct on Door43.

**Comment by phillip-hopper** [comment]
@jag3773 what is wrong on unfoldingword.org? Both sites are using the same font in Firefox.

**Comment by phillip-hopper** [comment]
@jag3773 Where should I make the css changes to api.unfoldingword.org?

**Comment by jag3773** [comment]
This is what exports those web viewers: https://github.com/unfoldingWord-dev/tools/blob/master/obs/js/reveal_export.py.

**Comment by phillip-hopper** [comment]
@jag3773 - Can you test this to confirm it is fixed?

**Comment by jag3773** [comment]
:+1:
